services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PAYMENT_USER}
      POSTGRES_PASSWORD: ${PAYMENT_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB}
    ports:
      - "${DB_PORT}:5432"
    container_name: db-payment-gateaway-core
    volumes:
      - db-payment-gateaway-core-data:/var/lib/postgresql/data

volumes:
  db-payment-gateaway-core-data: